# Generated by Django 5.2 on 2025-04-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
