# Generated by Django 5.2 on 2025-04-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_item_available_item_preorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hit',
            field=models.BooleanField(default=False),
        ),
    ]
